"""
pract_stub.py — Practify Protocol anchor stub.

Generated by `practify init`.

DELETE THIS FILE to disable all anchors.
KEEP THIS FILE without the practify package installed: decorators become no-ops.
Code continues to run without modification.

Three operating states:
  Full:    pract_stub.py EXISTS + practify installed → anchors register & validate
  Silent:  pract_stub.py EXISTS + practify NOT installed → anchors are no-ops
  Clean:   pract_stub.py DELETED → remove `from pract_stub import ...` line

To fully remove practify from this project:
  1. Delete this file (pract_stub.py)
  2. Delete the practify/ directory (or pip uninstall practify)
  3. (Optional) Remove `from pract_stub import ...` from source files.
     Single-command cleanup: grep -rl "pract_stub" . | xargs sed -i '/pract_stub/d'
"""

try:
    from practify import test as _pract_test, i_dont_know as _pract_idk
except ImportError:
    # practify not installed — anchors silently become no-ops.
    # @pt and @idk decorators return the function unchanged.
    def _pract_test(description, test_fn):
        def decorator(f):
            return f
        return decorator

    def _pract_idk(what):
        def decorator(f):
            return f
        return decorator


# Short aliases for source-file use:
#   from pract_stub import test as pt, i_dont_know as idk
test = _pract_test
i_dont_know = _pract_idk
