"""
anchorlaw_stub.py — Anchorlaw Protocol anchor stub.

Generated by `anchorlaw init`.

DELETE THIS FILE to disable all anchors.
KEEP THIS FILE without the anchorlaw package installed: decorators become no-ops.
Code continues to run without modification.

Three operating states:
  Full:    anchorlaw_stub.py EXISTS + anchorlaw installed → anchors register & validate
  Silent:  anchorlaw_stub.py EXISTS + anchorlaw NOT installed → anchors are no-ops
  Clean:   anchorlaw_stub.py DELETED → remove `from anchorlaw_stub import ...` line

To fully remove anchorlaw from this project:
  1. Delete this file (anchorlaw_stub.py)
  2. Delete the anchorlaw/ directory (or pip uninstall anchorlaw)
  3. (Optional) Remove `from anchorlaw_stub import ...` from source files.
     Single-command cleanup: grep -rl "anchorlaw_stub" . | xargs sed -i '/anchorlaw_stub/d'
"""

try:
    from anchorlaw import test as _anchor_test, i_dont_know as _anchor_idk
except ImportError:
    # anchorlaw not installed — anchors silently become no-ops.
    # @anchor.test and @anchor.idk decorators return the function unchanged.
    def _anchor_test(description, test_fn, source=""):
        def decorator(f):
            return f
        return decorator

    def _anchor_idk(what, source=""):
        def decorator(f):
            return f
        return decorator


# Short aliases for source-file use:
#   from anchorlaw_stub import test as pt, i_dont_know as idk
test = _anchor_test
i_dont_know = _anchor_idk
